name: Cypress E2E Tests with Auto-Healing

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Start React development server and wait
      run: |
        echo "Starting React development server..."
        npm start &
        
        echo "Waiting for server to be ready..."
        # Wait for the server to start
        sleep 15
        
        # Check if server is responding
        for i in {1..30}; do
          if curl -f -s http://localhost:9300 > /dev/null; then
            echo "✅ Server is ready and responding!"
            break
          else
            echo "⏳ Waiting for server... (attempt $i/30)"
            sleep 2
          fi
        done
        
        # Final check
        if ! curl -f -s http://localhost:9300 > /dev/null; then
          echo "❌ Server failed to start properly"
          exit 1
        fi
        
    - name: Run Cypress tests
      run: |
        echo "Running Cypress tests..."
        npm run cypress
        
    - name: Upload Cypress screenshots on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        if-no-files-found: ignore
        
    - name: Upload DOM content on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-dom-content
        path: cypress/failures
        if-no-files-found: ignore
        
    - name: Auto-healing notification
      if: failure()
      run: |
        echo "🚨 Test failure detected! Auto-healing pipeline triggered."
        echo "Failure details will be sent to auto-healing system."
        echo "Workflow run ID: ${{ github.run_id }}"
        echo "Failure URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        # TODO: Add auto-healing integration here
        # - Send failure details to AI system
        # - Generate potential fixes
        # - Create pull request with fixes 